import type { StatementData, StatementSection, StatementType } from '@/types'

// ── CSV ───────────────────────────────────────────────────────

function flattenSections(sections: StatementSection[], depth = 0): string[] {
  const rows: string[] = []
  for (const s of sections) {
    const indent = '  '.repeat(depth)
    const label = `"${indent}${s.label.replace(/"/g, '""')}"`
    const amount = s.amount.toFixed(2)
    rows.push(`${label},${amount}`)
    if (s.children?.length) {
      rows.push(...flattenSections(s.children, depth + 1))
    }
  }
  return rows
}

export function toCSV(data: StatementData, _type: StatementType): Buffer {
  const lines = ['Label,Amount', ...flattenSections(data.sections)]
  return Buffer.from(lines.join('\n'), 'utf-8')
}

// ── XLSX ──────────────────────────────────────────────────────

export async function toXLSX(data: StatementData, _type: StatementType): Promise<Buffer> {
  const { utils, write } = await import('xlsx')

  const rows: (string | number)[][] = [['Label', 'Amount']]

  function addRows(sections: StatementSection[], depth = 0) {
    for (const s of sections) {
      rows.push(['  '.repeat(depth) + s.label, s.amount])
      if (s.children?.length) addRows(s.children, depth + 1)
    }
  }

  addRows(data.sections)

  const ws = utils.aoa_to_sheet(rows)
  const wb = utils.book_new()
  utils.book_append_sheet(wb, ws, 'Statement')

  return Buffer.from(write(wb, { type: 'buffer', bookType: 'xlsx' }))
}

// ── PDF ───────────────────────────────────────────────────────

export async function toPDF(data: StatementData, type: StatementType): Promise<Buffer> {
  // Dynamic import keeps @react-pdf/renderer out of the client bundle
  const ReactPDF = await import('@react-pdf/renderer')
  const { Document, Page, Text, View, StyleSheet, renderToBuffer } = ReactPDF
  const { createElement: h } = await import('react')

  const typeLabel: Record<StatementType, string> = {
    pnl: 'Profit & Loss',
    balance_sheet: 'Balance Sheet',
    cash_flow: 'Statement of Cash Flows',
  }

  const styles = StyleSheet.create({
    page: { fontFamily: 'Helvetica', padding: 48, fontSize: 10, color: '#1a1a1a' },
    title: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 4 },
    subtitle: { fontSize: 10, color: '#666', marginBottom: 24 },
    sectionHeader: { fontFamily: 'Helvetica-Bold', fontSize: 11, marginTop: 16, marginBottom: 4, paddingBottom: 4, borderBottomWidth: 1, borderBottomColor: '#e5e5e5' },
    rowIndent1: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 1, paddingLeft: 12 },
    rowIndent2: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 1, paddingLeft: 24, color: '#666' },
    totalRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, marginTop: 8, borderTopWidth: 1, borderTopColor: '#1a1a1a', fontFamily: 'Helvetica-Bold' },
    label: { flex: 1 },
    amount: { textAlign: 'right', fontFamily: 'Helvetica', minWidth: 80 },
    amountBold: { textAlign: 'right', fontFamily: 'Helvetica-Bold', minWidth: 80 },
  })

  const fmt = (n: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n)

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function renderSection(section: StatementSection, depth = 0): any {
    const isTotal = section.label.startsWith('NET') || section.label.startsWith('TOTAL') || section.label.startsWith('GROSS')
    const rowStyle = isTotal ? styles.totalRow : depth === 0 ? styles.sectionHeader : depth === 1 ? styles.rowIndent1 : styles.rowIndent2
    const amtStyle = isTotal ? styles.amountBold : styles.amount

    return h(View, { key: section.label },
      h(View, { style: rowStyle },
        h(Text, { style: styles.label }, section.label),
        h(Text, { style: amtStyle }, fmt(section.amount))
      ),
      ...(section.children?.map(c => renderSection(c, depth + 1)) ?? [])
    )
  }

  const doc = h(Document, null,
    h(Page, { size: 'A4', style: styles.page },
      h(Text, { style: styles.title }, typeLabel[type]),
      h(Text, { style: styles.subtitle }, 'Generated by Humaris'),
      ...data.sections.map(s => renderSection(s))
    )
  )

  return renderToBuffer(doc as Parameters<typeof renderToBuffer>[0])
}

// ── Dispatcher ────────────────────────────────────────────────

export async function exportStatement(
  data: StatementData,
  type: StatementType,
  format: 'pdf' | 'xlsx' | 'csv'
): Promise<{ buffer: Buffer; contentType: string; filename: string }> {
  const typeLabel: Record<StatementType, string> = {
    pnl: 'PnL',
    balance_sheet: 'BalanceSheet',
    cash_flow: 'CashFlow',
  }
  const base = typeLabel[type]

  if (format === 'csv') {
    return {
      buffer: toCSV(data, type),
      contentType: 'text/csv',
      filename: `${base}.csv`,
    }
  }
  if (format === 'xlsx') {
    return {
      buffer: await toXLSX(data, type),
      contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      filename: `${base}.xlsx`,
    }
  }
  return {
    buffer: await toPDF(data, type),
    contentType: 'application/pdf',
    filename: `${base}.pdf`,
  }
}
